### ISSUE TITLE
Wix embedded mysql

### ISSUE THREAD

**Issue by michaeljamieson10** [josephtaylor/tennessee-covid-19#11]
Hello! I do not believe there is another way of contacting you on github. I see you had recent involvement in the wix embedded mysql for testing. I see that it has not been added onto for some time. Is there anyway to get involved in this project?

**Comment by josephtaylor** [comment]
Hi there, I'm not a maintainer of that or anything, I'm not sure what the status of the project is. We've actually switched to using testcontainers for testing. If you're familiar with docker, it works really really well.

**Comment by michaeljamieson10** [comment]
Thank you for the suggestion and response! I will look into docker. We really liked wix embedded mysql as it ran real mysql and its own database off a our schema.
